spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/tcpDb
    username: sa


  sql:
    init:
      mode: always
#      schema-locations:
#        - classpath:schema-h2.sql
#      data-locations:
#        - classpath:data-h2.sql

  # jpa 설정
  jpa:
    defer-datasource-initialization: true
    hibernate: # hibernate 사용 설정
      ddl-auto: create-drop # create,create-drop,update,none
      #naming:
      #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
